services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "node backend/app.js"
    autoDeploy: true
    
  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "serve -s frontend/dist/frontend -l 3000"
    autoDeploy: true
